"""Render an analysis into a downloadable PDF report.

Security properties:
* every value is HTML-escaped by Jinja2 autoescaping; the model's report
  passes through :mod:`investing_engine.reporting.markdown`, which emits only
  a fixed set of tags and no links;
* WeasyPrint runs with a URL fetcher that refuses every request, so content
  cannot make the renderer read local files or reach the network (SSRF);
* the only unescaped content is SVG generated by this module's own charts.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, NoReturn

import pandas as pd
from jinja2 import Environment, FileSystemLoader, select_autoescape
from markupsafe import Markup

from investing_engine.reporting import charts
from investing_engine.reporting.markdown import to_html

_TEMPLATES = Path(__file__).parent / "templates"
_env = Environment(
    loader=FileSystemLoader(_TEMPLATES),
    autoescape=select_autoescape(["html", "j2"], default_for_string=True),
    trim_blocks=True,
    lstrip_blocks=True,
)


class BlockedFetchError(PermissionError):
    pass


def refuse_fetch(url: str, *args: Any, **kwargs: Any) -> NoReturn:
    """WeasyPrint URL fetcher that blocks all external and local resources."""
    raise BlockedFetchError(f"Resource loading is disabled: {url[:80]}")


@dataclass
class InstrumentSection:
    symbol: str
    name: str
    technical: dict[str, Any] | None = None
    risk: float | None = None
    series: pd.DataFrame | None = None
    history: Sequence[dict[str, Any]] = field(default_factory=list)


def _trusted(html: str) -> Markup:
    """Mark HTML produced by this package (chart SVG, escaped Markdown) as safe.

    Only ever called on output of :mod:`charts` and :func:`markdown.to_html`,
    neither of which passes untrusted markup through.
    """
    return Markup(html)  # noqa: S704


def _fmt(value: Any) -> str:
    if value is None:
        return "–"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, float):
        return f"{value:,.4f}".rstrip("0").rstrip(".") if abs(value) < 10 else f"{value:,.2f}"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def _indicator_rows(technical: dict[str, Any]) -> list[tuple[tuple[str, str], tuple[str, str]]]:
    fields = [
        ("EMA34", "ema34"), ("EMA89", "ema89"), ("Above EMA34", "price_above_ema34"),
        ("MACD", "macd"), ("MACD signal", "macd_signal"), ("Bollinger %B", "bb_pct"),
        ("Channel position", "channel_position"), ("Momentum divergence", "momentum_divergence"),
        ("ATR", "atr"), ("ADX", "adx"), ("Stochastic %K", "stoch_k"), ("OBV", "obv"),
    ]  # fmt: skip
    cells = [(label, _fmt(technical.get(key))) for label, key in fields if key in technical]
    if len(cells) % 2:
        cells.append(("", ""))
    return list(zip(cells[::2], cells[1::2], strict=True))


def render_html(
    *,
    report: str,
    sections: Sequence[InstrumentSection],
    checks: dict[str, Any],
    injection_flags: Sequence[str],
    usage: dict[str, dict[str, int]],
    sources: Sequence[dict[str, str]],
    reference: str,
    generated_at: datetime | None = None,
) -> str:
    instruments = []
    for section in sections:
        svgs: list[Markup] = []
        if section.series is not None and not section.series.empty:
            title = "Price, EMA34/89 and Bollinger bands"
            svgs.append(_trusted(charts.price_chart(section.series, title=title)))
            predicted = (section.technical or {}).get("predicted_next_rsi")
            svgs.append(_trusted(charts.rsi_chart(section.series, predicted=predicted)))
        if history_svg := charts.history_chart(section.history):
            svgs.append(_trusted(history_svg))
        instruments.append(
            {
                "symbol": section.symbol,
                "name": section.name,
                "technical": section.technical,
                "risk": section.risk,
                "charts": svgs,
                "indicator_rows": _indicator_rows(section.technical or {}),
            }
        )

    tokens = sum(u.get("input_tokens", 0) + u.get("output_tokens", 0) for u in usage.values())
    score = checks.get("grounding_score")
    return _env.get_template("report.html.j2").render(
        symbols=[s.symbol for s in sections],
        instruments=instruments,
        report_html=_trusted(to_html(report)),
        grounding="–" if score is None else f"{score:.0%}",
        ungrounded=checks.get("ungrounded_figures") or [],
        injection_flags=list(injection_flags),
        tokens=f"{tokens:,}" if tokens else "–",
        sources=sources,
        reference=reference,
        generated_at=(generated_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M"),
    )


def render_pdf(**kwargs: Any) -> bytes:
    from weasyprint import HTML

    html = render_html(**kwargs)
    pdf: bytes = HTML(string=html, url_fetcher=refuse_fetch).write_pdf()
    return pdf
